- name: Deploy Palworld systemd service
  ansible.builtin.template:
    src: palworld.service.j2
    dest: /etc/systemd/system/palworld.service
    mode: '0644'

- name: Enable and start Palworld server
  ansible.builtin.systemd:
    name: palworld.service
    state: started
    enabled: true
    daemon_reload: true

- name: Wait a few seconds for the Palworld server to initialize
  ansible.builtin.pause:
    seconds: 5