---
# Directory where the Palworld server will be installed
palworld_server_dir: /home/steam/palworld_server

# Those settings came from the default configuration file DefaultPalWorldSettings.ini found in the installation directory
palworld_server_settings:
  Difficulty: None
  RandomizerType: None
  RandomizerSeed: ""
  bIsRandomizerPalLevelRandom: false
  DayTimeSpeedRate: 1.000000
  NightTimeSpeedRate: 1.000000
  ExpRate: 1.000000
  PalCaptureRate: 1.000000
  PalSpawnNumRate: 1.000000
  PalDamageRateAttack: 1.000000
  PalDamageRateDefense: 1.000000
  PlayerDamageRateAttack: 1.000000
  PlayerDamageRateDefense: 1.000000
  PlayerStomachDecreaceRate: 1.000000
  PlayerStaminaDecreaceRate: 1.000000
  PlayerAutoHPRegeneRate: 1.000000
  PlayerAutoHpRegeneRateInSleep: 1.000000
  PalStomachDecreaceRate: 1.000000
  PalStaminaDecreaceRate: 1.000000
  PalAutoHPRegeneRate: 1.000000
  PalAutoHpRegeneRateInSleep: 1.000000
  BuildObjectHpRate: 1.000000
  BuildObjectDamageRate: 1.000000
  BuildObjectDeteriorationDamageRate: 1.000000
  CollectionDropRate: 1.000000
  CollectionObjectHpRate: 1.000000
  CollectionObjectRespawnSpeedRate: 1.000000
  EnemyDropItemRate: 1.000000
  DeathPenalty: All
  bEnablePlayerToPlayerDamage: false
  bEnableFriendlyFire: false
  bEnableInvaderEnemy: true
  bActiveUNKO: false
  bEnableAimAssistPad: true
  bEnableAimAssistKeyboard: false
  DropItemMaxNum: 3000
  DropItemMaxNum_UNKO: 100
  BaseCampMaxNum: 128
  BaseCampWorkerMaxNum: 15
  DropItemAliveMaxHours: 1.000000
  bAutoResetGuildNoOnlinePlayers: false
  AutoResetGuildTimeNoOnlinePlayers: 72.000000
  GuildPlayerMaxNum: 20
  BaseCampMaxNumInGuild: 4
  PalEggDefaultHatchingTime: 72.000000
  WorkSpeedRate: 1.000000
  AutoSaveSpan: 30.000000
  bIsMultiplay: false
  bIsPvP: false
  bHardcore: false
  bPalLost: false
  bCharacterRecreateInHardcore: false
  bCanPickupOtherGuildDeathPenaltyDrop: false
  bEnableNonLoginPenalty: true
  bEnableFastTravel: true
  bIsStartLocationSelectByMap: true
  bExistPlayerAfterLogout: false
  bEnableDefenseOtherGuildPlayer: false
  bInvisibleOtherGuildBaseCampAreaFX: false
  bBuildAreaLimit: false
  ItemWeightRate: 1.000000
  CoopPlayerMaxNum: 4
  ServerPlayerMaxNum: 32
  ServerName: "Default Palworld Server"
  ServerDescription: ""
  AdminPassword: ""
  ServerPassword: ""
  PublicPort: 8211
  PublicIP: ""
  RCONEnabled: false
  RCONPort: 25575
  Region: ""
  bUseAuth: true
  BanListURL: "https://api.palworldgame.com/api/banlist.txt"
  RESTAPIEnabled: false
  RESTAPIPort: 8212
  bShowPlayerList: false
  ChatPostLimitPerMinute: 30
  CrossplayPlatforms:
    - Steam
    - Xbox
    - PS5
    - Mac
  bIsUseBackupSaveData: true
  LogFormatType: Text
  bIsShowJoinLeftMessage: true
  SupplyDropSpan: 180
  EnablePredatorBossPal: true
  MaxBuildingLimitNum: 0
  ServerReplicatePawnCullDistance: 15000.000000
  bAllowGlobalPalboxExport: true
  bAllowGlobalPalboxImport: false
  EquipmentDurabilityDamageRate: 1.000000
  ItemContainerForceMarkDirtyInterval: 1.000000
  ItemCorruptionMultiplier: 1.000000