---
# Here override the palworld server settings as needed
palworld_server_settings:
  ServerName: "Palworld Server"
  ServerDescription: "GL HF in Palworld!"
  #ExpRate: 2.000000
  #PalSpawnNumRate: 2.000000
  #DeathPenalty: "None"
  #BaseCampWorkerMaxNum: 25
  #bEnableInvaderEnemy: false
  EnemyDropItemRate: 2.500000
  PalEggDefaultHatchingTime: 12.000000
  CollectionDropRate: 2.000000
